[package]
name = "psu"
version = "0.1.0"
edition = "2021"
authors = ["IwantHAPPINESS"]
description = "Password storage utility."

[profile.release]
lto = true

[dependencies]
clap = { version = "4.5.18", features = ["derive"] }
colored = "2.1.0"
rusqlite = { version = "0.32.1", features = ["bundled"] }
