[package]
name = "psu"
version = "1.0.3"
edition = "2021"
license = "MIT"
authors = ["IwantHAPPINESS"]
description = "Password storage utility."

[profile.release]
lto = true

[dependencies]
clap = { version = "4.5.18", features = ["derive"] }
colored = "2.1.0"
directories = "5.0.1"
rusqlite = { version = "0.32.1", features = ["bundled"] }
